/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {

    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testArrayDiceRolls() {
        int[] arr = new int[4];
        int size = arr.length;
        assertEquals(
                "Expected an array of length 4",
                size,
                Library.roll(4).length);
    }

    @Test public void testIfTrue() {
        assertEquals(
                "Expected true as the answer",
                true,
                Library.duplicates(new int[] {3, 4, 1, 3})
        );
    }

    @Test public void testAverage() {
        assertEquals(
                "Should return 3",
                3,
                Library.averages(new int[]{3, 5, 2, 2})
        );
    }

    @Test public void testNestedArrayAverage() {
        int[] goodAnswer = {1,1,1,3};
        int[][] origArr = {
                {1,2,3,4},
                {1,1,1,3},
                {3,2,1,1},
                {3,2,1,4}
        };
        assertArrayEquals(
                "The subarray with the lowest average should return as [1,1,1,3].",
                goodAnswer,
                Library.nestedAverages(origArr)
        );
    }
}
